-- Root file for Bootstrapping Neovim plugins
-- and associated config

require "user.alpha"
require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.gitsigns"
require "user.autocommands"
require "user.cmp"
require "user.telescope"
require "user.bufferline"
require "user.colorscheme"
require "user.treesitter"
require "user.nvim-tree"
require "user.autopairs"
require "user.lsp"
require "user.whichkey"
require "user.lualine"
require "user.icons"
require "user.toggleterm"
require "user.indentline"
require "user.comment"
require "user.copilot"
