-- Root file for Bootstrapping Neovim plugins
-- and associated config

require "user.alpha"
require "user.autocommands"
require "user.autopairs"
require "user.bufferline"
require "user.catppuccin"
require "user.cmp"
require "user.colorscheme"
require "user.comment"
require "user.compiler-explorer"
-- require "user.copilot"
require "user.cybu"
require "user.due"
require "user.gitsigns"
require "user.glow"
require "user.icon-picker"
require "user.icons"
require "user.indentline"
require "user.lsp"
require "user.lualine"
require "user.keymaps"
require "user.leap"
require "user.material"
require "user.notify"
require "user.numb"
require "user.nvim-tree"
require "user.options"
require "user.overlength"
require "user.plugins"
require "user.range-highlight"
require "user.rust-tools"
require "user.scrollbar"
require "user.symbols-outline"
require "user.telescope"
require "user.todo-comments"
require "user.transparent"
require "user.treesitter"
require "user.treesitter-context"
require "user.trouble"
require "user.toggleterm"
require "user.whichkey"
