-- Root file for Bootstrapping Neovim plugins
-- and associated config

require "user.alpha"
require "user.autocommands"
require "user.autopairs"
require "user.bufferline"
require "user.cmp"
require "user.colorscheme"
require "user.comment"
require "user.due"
require "user.gitsigns"
require "user.glow"
require "user.icons"
require "user.indentline"
require "user.lsp"
require "user.lualine"
require "user.keymaps"
require "user.notify"
require "user.numb"
require "user.nvim-tree"
require "user.options"
require "user.plugins"
require "user.range-highlight"
require "user.rust-tools"
require "user.symbols-outline"
require "user.telescope"
require "user.treesitter"
require "user.treesitter-context"
require "user.toggleterm"
require "user.whichkey"
-- require "user.copilot"
